local newFormatTemplate = {
  {
    Bg={
      Base={
        Tex={{"",""}},
        Tilt=false,
        OffsetY=0.17,
        Anim=true,
        ScaleSoft=false,
        ClampTiling=false,
      },
      Overlay={ -- is meant to be displayed overtop Base
        Tex="",
        Float=true,
        FloatFactor=2.0,
        OffsetY=0.12,
        FlashEffect=true,
        Tilt=true,
      },
      Layer={
        Tex={{"",""}},
        ScaleHard=false,
        Brighten=0.6,
      },
      u={
        Pivot=0.36
      },
    },
    Center={
      Tex={{"",""}},
      u={
        Scale=2.8,
        Pulse=true,
        Float=true,
        FloatFactor=0.5,
        FloatXFactor=0,
        FloatRotationFactor=0,
        FadeEffect=true,
        Tilt=false,
        Anim=true,
        OffsetY=-0.1,
        Glow=false,
        Rotate=false,
      },
      LayerEffect={
        Tex="",
        Fade=true,
        Rotate=true,
        RotateSpeed=-2.0,
        DodgeBlend=true,
        Glow=true,
        Alpha=0.7,
        Scale=0.5,
      },
    },
    Tunnel={ -- todo: give option to do sth with blend mode
      Tex={{"",""}},
      u={
        Stretch=0.3,
        ScaleX=0.8,
        ScaleY=0.9,
        Fog=10.0,
        FlashEffect=true,
        VortexEffect=false,
        VortexFactor=1.0,
        DodgeBlend=false
      }
    },
    Particle={
      Tex={{"",""}},
      u={
        Speed=0.3,
        OffsetY=-0.02,
        Amount=3,
        Scale=1.0,
        ExtraRotation=0.125
      },
    },
    luaParticleEffect={
      particles={
        {"star-particle.png", 32}
      }
    },
    speed=0.6,
  }
}